<?php

require_once PROJECT_ROOT . '/engine/lib/internal/ConfigSimple/Config.class.php';

/**
 * Test class for Config.
 * Generated by PHPUnit on 2011-12-27 at 02:29:25.
 */
class ConfigTest extends PHPUnit_Framework_TestCase
{
	/**
	 * @dataProvider setProvider
	 * @param $sKey
	 * @param $value
	 * @param $sMessage
	 */
    public function testSet($sKey,$value,$sMessage)
    {
		Config::Set($sKey,$value,'test');
		$this->assertEquals($value,Config::Get($sKey,'test'),$sMessage);
    }

	/**
	 * В прошлом тесте мы положили в конфиг массив
	 * Пробуем достать его значение
	 * @depends testSet
	 */
	public function testSetArray(){
		$this->assertEquals('test',Config::Get('testArray.test','test'));
	}

	/**
	 * @return array
	 */
	public function setProvider(){
		return array(
			array('testName','testValue','plain text'),
			array('testBigArray',array(
				'key1'=>array(
					'key2'=>array('some'=>'stuff'),
					'key3'=>array('another'=>'one'),
					'sdfs'=>'hhh'),
				'last'=>'one'
			),'bigArray'),
			array('testArray',array('test'=>'test'),'array')
		);
	}


	/**
	 * Проверка на то как отрабатывает кеш
	 * Ситуация когда нам нужно получить значение из конфига
	 * @depends testSetArray
	 */
	public function testRegetArray(){
		//получим значение, чтобы оно гарантированно легло в кеш
		Config::Get('testArray','test');
		//изменим значение по адресу testArray.test
		Config::Set('testArray',array('test'=>'test1'),'test');
		$this->assertEquals('test1',Config::Get('testArray.test','test'));
	}

	/**
	 * Проверка на то как отрабатывает кеш
	 * Ситуация когда нам нужно получить массив из конфига
	 * @depends testSetArray
	 */
	public function testRegetBigArray(){
		//получим значение, чтобы оно гарантированно легло в кеш
		Config::Get('testBigArray.key1.key3','test');
		//изменим значение по адресу testBigArray.key1.key3.another
		Config::Set('testBigArray',array(
						'key1'=>array(
							'key2'=>array('some'=>'stuff'),
							'key3'=>array('another'=>'stuff'),
							'sdfs'=>'hhh'),
						'last'=>'one'
					),'test');
		$this->assertEquals(array('another'=>'stuff'),Config::Get('testBigArray.key1.key3','test'));
	}

	public function testNewFileAppend(){
		//Читаем конфиг
		Config::LoadFromFile(PROJECT_ROOT . '/config/config.local.php',true,'test');
		//Изменим значение на произвольное
		Config::Set('view.noindex','adasdasdfasdffdsa','test');
		//получим значение, чтобы оно гарантированно легло в кеш
		Config::Get('view.noindex','test');
		//Перечитаем конфиг
		Config::LoadFromFile(PROJECT_ROOT . '/config/config.local.php',true,'test');
		//убедимся что значения которые мы внесли - затерлись
		 $this->assertNotEquals('adasdasdfasdffdsa',Config::Get('view.noindex','test'));
	}

}
?>